/**
 * SyncOffset Core Object Registry — metadata index.
 * Machine-readable companion to docs/SYNCOFFSET_CORE_OBJECT_REGISTRY.md
 */

import type { CoreObjectKind } from "./kinds";

export type CoreObjectRegistryEntry = {
  readonly kind: CoreObjectKind;
  readonly isImmutableSource: boolean;
  readonly isDerivedOnly: boolean;
  readonly isCalendarAuthority: boolean;
  readonly relationshipTargets: ReadonlyArray<CoreObjectKind>;
};

export const CORE_OBJECT_REGISTRY: Record<CoreObjectKind, CoreObjectRegistryEntry> = {
  show: {
    kind: "show",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["season", "episode", "shoot-day", "department", "location", "vendor", "asset"],
  },
  season: {
    kind: "season",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["show", "episode"],
  },
  episode: {
    kind: "episode",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["show", "scene", "shoot-day"],
  },
  department: {
    kind: "department",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["show", "crew-member", "crew-requirement", "crew-assignment", "department-package"],
  },
  "crew-requirement": {
    kind: "crew-requirement",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["department", "scene", "breakdown-element", "department-package", "crew-assignment"],
  },
  "shoot-day": {
    kind: "shoot-day",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: true,
    relationshipTargets: [
      "scene",
      "location",
      "document",
      "crew-member",
      "cast-member",
      "company-move",
      "asset",
      "shipment",
      "transport-order",
    ],
  },
  "prep-day": {
    kind: "prep-day",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["department", "shoot-day"],
  },
  "wrap-day": {
    kind: "wrap-day",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["department", "shoot-day"],
  },
  "company-move": {
    kind: "company-move",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["shoot-day", "location", "asset", "crew-member"],
  },
  script: {
    kind: "script",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["script-revision", "scene"],
  },
  "script-revision": {
    kind: "script-revision",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["script", "scene", "revision-change", "document", "breakdown-element"],
  },
  "revision-change": {
    kind: "revision-change",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["script-revision", "scene"],
  },
  scene: {
    kind: "scene",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "episode",
      "script-revision",
      "revision-change",
      "shoot-day",
      "location",
      "cast-member",
      "character",
      "cast-requirement",
      "cast-assignment",
      "crew-requirement",
      "crew-assignment",
      "asset",
      "media",
      "element",
      "breakdown-element",
      "bg-requirement",
      "department-package",
      "transport-order",
    ],
  },
  element: {
    kind: "element",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["scene", "bg-requirement", "breakdown-element"],
  },
  "breakdown-element": {
    kind: "breakdown-element",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["scene", "script-revision", "bg-requirement", "department-package", "asset", "location"],
  },
  "bg-requirement": {
    kind: "bg-requirement",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["scene", "element", "breakdown-element", "bg-assignment", "script-revision"],
  },
  "director-note": {
    kind: "director-note",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["script-revision", "scene", "location", "department-package", "media", "approval-record"],
  },
  "creative-reference": {
    kind: "creative-reference",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "script-revision",
      "scene",
      "location",
      "shoot-day",
      "department-package",
      "media",
      "cast-member",
    ],
  },
  "department-package": {
    kind: "department-package",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "director-note",
      "tech-pack",
      "creative-reference",
      "scene",
      "location",
      "document",
      "media",
      "approval-record",
    ],
  },
  "tech-pack": {
    kind: "tech-pack",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["department-package", "document", "media", "approval-record"],
  },
  "approval-record": {
    kind: "approval-record",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["director-note", "department-package", "tech-pack"],
  },
  person: {
    kind: "person",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["department"],
  },
  character: {
    kind: "character",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["script-revision", "scene", "cast-requirement", "cast-assignment"],
  },
  "cast-requirement": {
    kind: "cast-requirement",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["scene", "character", "script-revision", "cast-assignment"],
  },
  "cast-member": {
    kind: "cast-member",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["cast-assignment", "scene", "shoot-day", "document", "generated-output"],
  },
  "cast-assignment": {
    kind: "cast-assignment",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["character", "cast-member", "cast-requirement", "scene", "shoot-day", "generated-output"],
  },
  "background-performer": {
    kind: "background-performer",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["shoot-day", "scene", "bg-assignment", "document", "generated-output"],
  },
  "bg-assignment": {
    kind: "bg-assignment",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["background-performer", "bg-requirement", "shoot-day", "scene", "generated-output"],
  },
  "stunt-performer": {
    kind: "stunt-performer",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["scene", "shoot-day", "document"],
  },
  "crew-member": {
    kind: "crew-member",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["department", "crew-assignment", "shoot-day", "document", "generated-output"],
  },
  "crew-assignment": {
    kind: "crew-assignment",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["crew-member", "crew-requirement", "shoot-day", "scene", "generated-output"],
  },
  location: {
    kind: "location",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["shoot-day", "scene", "permit", "media", "company-move"],
  },
  permit: {
    kind: "permit",
    isImmutableSource: true,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["location"],
  },
  asset: {
    kind: "asset",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["scene", "shipment", "vendor"],
  },
  vendor: {
    kind: "vendor",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["asset", "purchase-order", "shipment", "document"],
  },
  "purchase-order": {
    kind: "purchase-order",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["vendor", "asset"],
  },
  "transport-order": {
    kind: "transport-order",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["shoot-day", "asset", "vendor", "shipment"],
  },
  shipment: {
    kind: "shipment",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["transport-order", "asset", "vendor", "location"],
  },
  return: {
    kind: "return",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["asset", "vendor"],
  },
  document: {
    kind: "document",
    isImmutableSource: true,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["show", "shoot-day", "scene", "location", "asset", "person", "vendor"],
  },
  "generated-output": {
    kind: "generated-output",
    isImmutableSource: false,
    isDerivedOnly: true,
    isCalendarAuthority: false,
    relationshipTargets: ["document", "shoot-day", "transport-order"],
  },
  media: {
    kind: "media",
    isImmutableSource: true,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["scene", "shoot-day", "location", "asset", "person"],
  },
  "risk-evaluation": {
    kind: "risk-evaluation",
    isImmutableSource: false,
    isDerivedOnly: true,
    isCalendarAuthority: false,
    relationshipTargets: ["shoot-day", "location", "asset", "shipment", "vendor"],
  },
};
