/**
 * SyncOffset Core Object Registry — metadata index.
 * Machine-readable companion to docs/SYNCOFFSET_CORE_OBJECT_REGISTRY.md
 */

import type { CoreObjectKind } from "./kinds";

export type CoreObjectRegistryEntry = {
  readonly kind: CoreObjectKind;
  readonly isImmutableSource: boolean;
  readonly isDerivedOnly: boolean;
  readonly isCalendarAuthority: boolean;
  readonly relationshipTargets: ReadonlyArray<CoreObjectKind>;
};

export const CORE_OBJECT_REGISTRY: Record<CoreObjectKind, CoreObjectRegistryEntry> = {
  show: {
    kind: "show",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "season",
      "episode",
      "shooting-schedule",
      "production-calendar",
      "shoot-day",
      "department",
      "location",
      "vendor",
      "asset",
      "production-cost",
      "department-cost",
      "cost-report",
    ],
  },
  season: {
    kind: "season",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["show", "episode"],
  },
  episode: {
    kind: "episode",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["show", "scene", "shoot-day", "production-cost", "department-cost", "cost-report"],
  },
  department: {
    kind: "department",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "show",
      "crew-member",
      "crew-requirement",
      "crew-assignment",
      "department-package",
      "purchase-order",
      "work-order",
      "work-order-task",
      "production-cost",
      "department-cost",
      "cost-report",
      "communication",
      "distribution-list",
    ],
  },
  "crew-requirement": {
    kind: "crew-requirement",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["department", "scene", "breakdown-element", "department-package", "crew-assignment"],
  },
  "production-calendar": {
    kind: "production-calendar",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: true,
    relationshipTargets: [
      "show",
      "shooting-schedule",
      "calendar-day",
      "calendar-revision",
      "calendar-package",
      "document",
      "generated-output",
      "communication",
    ],
  },
  "calendar-day": {
    kind: "calendar-day",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: true,
    relationshipTargets: ["production-calendar", "shoot-day", "company-move", "scene"],
  },
  "calendar-revision": {
    kind: "calendar-revision",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["production-calendar", "document"],
  },
  "calendar-package": {
    kind: "calendar-package",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["production-calendar", "source-document", "document", "generated-output"],
  },
  "shooting-schedule": {
    kind: "shooting-schedule",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "show",
      "scene",
      "script-revision",
      "shooting-schedule-revision",
      "shooting-schedule-package",
      "production-calendar",
      "source-document",
      "document",
      "generated-output",
    ],
  },
  "shooting-schedule-revision": {
    kind: "shooting-schedule-revision",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["shooting-schedule", "source-document", "document", "document-revision"],
  },
  "shooting-schedule-package": {
    kind: "shooting-schedule-package",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["shooting-schedule", "source-document", "document", "generated-output"],
  },
  callsheet: {
    kind: "callsheet",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "show",
      "shoot-day",
      "callsheet-revision",
      "callsheet-distribution",
      "callsheet-package",
      "generated-output",
      "production-calendar",
      "calendar-day",
      "shooting-schedule",
      "cast-assignment",
      "bg-assignment",
      "crew-assignment",
      "asset-assignment",
      "location-assignment",
      "transport-order",
      "scene",
      "document",
      "communication",
      "distribution-list",
    ],
  },
  communication: {
    kind: "communication",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "show",
      "scene",
      "set",
      "shoot-day",
      "callsheet",
      "work-order",
      "transport-order",
      "vendor",
      "location",
      "asset",
      "purchase-order",
      "shipment",
      "return",
      "production-calendar",
      "distribution-list",
      "communication-package",
      "generated-output",
      "document",
    ],
  },
  "distribution-list": {
    kind: "distribution-list",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["department", "show", "vendor", "crew-member", "person", "communication"],
  },
  "communication-package": {
    kind: "communication-package",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["communication", "generated-output", "document"],
  },
  "callsheet-revision": {
    kind: "callsheet-revision",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["callsheet", "document"],
  },
  "callsheet-distribution": {
    kind: "callsheet-distribution",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["callsheet"],
  },
  "callsheet-package": {
    kind: "callsheet-package",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["callsheet", "generated-output", "document"],
  },
  "work-order": {
    kind: "work-order",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "department",
      "scene",
      "set",
      "budget-requirement",
      "shoot-day",
      "work-order-task",
      "work-order-package",
      "generated-output",
      "document",
      "communication",
    ],
  },
  "work-order-task": {
    kind: "work-order-task",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["work-order", "shoot-day"],
  },
  "work-order-package": {
    kind: "work-order-package",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["work-order", "generated-output", "document"],
  },
  "shoot-day": {
    kind: "shoot-day",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "calendar-day",
      "callsheet",
      "work-order",
      "scene",
      "set",
      "location",
      "document",
      "crew-member",
      "cast-member",
      "cast-assignment",
      "bg-assignment",
      "crew-assignment",
      "company-move",
      "asset",
      "asset-assignment",
      "shipment",
      "transport-order",
      "shootday-assignment",
      "shootday-package",
      "generated-output",
      "location-assignment",
      "production-cost",
      "communication",
      "inventory-record",
    ],
  },
  "shootday-assignment": {
    kind: "shootday-assignment",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "shoot-day",
      "scene",
      "set",
      "location",
      "asset",
      "cast-assignment",
      "bg-assignment",
      "crew-assignment",
    ],
  },
  "shootday-package": {
    kind: "shootday-package",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["shoot-day", "source-document", "document", "generated-output"],
  },
  "prep-day": {
    kind: "prep-day",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["department", "shoot-day"],
  },
  "wrap-day": {
    kind: "wrap-day",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["department", "shoot-day"],
  },
  "company-move": {
    kind: "company-move",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["shoot-day", "location", "asset", "crew-member"],
  },
  script: {
    kind: "script",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["script-revision", "scene"],
  },
  "script-revision": {
    kind: "script-revision",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "script",
      "scene",
      "revision-change",
      "shooting-schedule",
      "source-document",
      "document",
      "breakdown-element",
    ],
  },
  "revision-change": {
    kind: "revision-change",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["script-revision", "scene"],
  },
  scene: {
    kind: "scene",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "episode",
      "script-revision",
      "revision-change",
      "shooting-schedule",
      "shoot-day",
      "set",
      "location",
      "cast-member",
      "character",
      "cast-requirement",
      "cast-assignment",
      "crew-requirement",
      "crew-assignment",
      "location-requirement",
      "location-assignment",
      "budget-requirement",
      "media",
      "element",
      "breakdown-element",
      "bg-requirement",
      "department-package",
      "transport-order",
      "vendor",
      "work-order",
      "communication",
    ],
  },
  set: {
    kind: "set",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "scene",
      "asset",
      "location",
      "budget-requirement",
      "department",
      "purchase-order",
      "work-order",
      "production-cost",
      "department-cost",
      "inventory-record",
    ],
  },
  "budget-requirement": {
    kind: "budget-requirement",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "scene",
      "breakdown-element",
      "set",
      "asset",
      "vendor",
      "location",
      "purchase-order",
      "work-order",
      "production-cost",
      "department-cost",
      "communication",
    ],
  },
  "asset-assignment": {
    kind: "asset-assignment",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "asset",
      "asset-instance",
      "set",
      "scene",
      "shoot-day",
      "location",
      "shipment",
      "transport-order",
    ],
  },
  "asset-instance": {
    kind: "asset-instance",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["asset", "set", "location", "vendor"],
  },
  "asset-package": {
    kind: "asset-package",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["asset", "set", "source-document", "document", "generated-output", "media"],
  },
  element: {
    kind: "element",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["scene", "bg-requirement", "breakdown-element"],
  },
  "breakdown-element": {
    kind: "breakdown-element",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "scene",
      "script-revision",
      "bg-requirement",
      "department-package",
      "asset",
      "location",
      "location-requirement",
      "budget-requirement",
    ],
  },
  "bg-requirement": {
    kind: "bg-requirement",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["scene", "element", "breakdown-element", "bg-assignment", "script-revision"],
  },
  "director-note": {
    kind: "director-note",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["script-revision", "scene", "location", "department-package", "media", "approval-record"],
  },
  "creative-reference": {
    kind: "creative-reference",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "script-revision",
      "scene",
      "location",
      "shoot-day",
      "department-package",
      "media",
      "cast-member",
    ],
  },
  "department-package": {
    kind: "department-package",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "director-note",
      "tech-pack",
      "creative-reference",
      "scene",
      "location",
      "document",
      "media",
      "approval-record",
    ],
  },
  "tech-pack": {
    kind: "tech-pack",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["department-package", "source-document", "document", "media", "approval-record"],
  },
  "approval-record": {
    kind: "approval-record",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["director-note", "department-package", "tech-pack"],
  },
  person: {
    kind: "person",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["department"],
  },
  character: {
    kind: "character",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["script-revision", "scene", "cast-requirement", "cast-assignment"],
  },
  "cast-requirement": {
    kind: "cast-requirement",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["scene", "character", "script-revision", "cast-assignment"],
  },
  "cast-member": {
    kind: "cast-member",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["cast-assignment", "scene", "shoot-day", "source-document", "document", "generated-output"],
  },
  "cast-assignment": {
    kind: "cast-assignment",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["character", "cast-member", "cast-requirement", "scene", "shoot-day", "generated-output"],
  },
  "background-performer": {
    kind: "background-performer",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["shoot-day", "scene", "bg-assignment", "source-document", "document", "generated-output"],
  },
  "bg-assignment": {
    kind: "bg-assignment",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["background-performer", "bg-requirement", "shoot-day", "scene", "generated-output"],
  },
  "stunt-performer": {
    kind: "stunt-performer",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["scene", "shoot-day", "document"],
  },
  "crew-member": {
    kind: "crew-member",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "department",
      "crew-assignment",
      "shoot-day",
      "source-document",
      "document",
      "generated-output",
    ],
  },
  "crew-assignment": {
    kind: "crew-assignment",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["crew-member", "crew-requirement", "shoot-day", "scene", "generated-output"],
  },
  "location-requirement": {
    kind: "location-requirement",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["scene", "breakdown-element", "location", "location-assignment", "department-package"],
  },
  "location-package": {
    kind: "location-package",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["location", "source-document", "document", "media", "scene"],
  },
  "location-assignment": {
    kind: "location-assignment",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["location", "location-requirement", "shoot-day", "scene", "company-move", "generated-output"],
  },
  location: {
    kind: "location",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "shoot-day",
      "scene",
      "permit",
      "media",
      "company-move",
      "location-requirement",
      "location-package",
      "location-assignment",
      "vendor",
      "asset",
      "communication",
      "inventory-record",
      "inventory-audit",
    ],
  },
  permit: {
    kind: "permit",
    isImmutableSource: true,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["location"],
  },
  asset: {
    kind: "asset",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "set",
      "asset-instance",
      "asset-assignment",
      "asset-package",
      "breakdown-element",
      "department",
      "budget-requirement",
      "shipment",
      "transport-order",
      "return",
      "purchase-order",
      "purchase-line",
      "vendor",
      "location",
      "brokerage-record",
      "production-cost",
      "communication",
      "inventory-record",
      "inventory-movement",
    ],
  },
  "inventory-record": {
    kind: "inventory-record",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "asset",
      "set",
      "location",
      "shoot-day",
      "inventory-movement",
      "inventory-audit",
      "inventory-package",
      "generated-output",
    ],
  },
  "inventory-movement": {
    kind: "inventory-movement",
    isImmutableSource: true,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["asset", "inventory-record", "location", "transport-order", "shipment", "set"],
  },
  "inventory-audit": {
    kind: "inventory-audit",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["location", "inventory-record", "set", "inventory-package"],
  },
  "inventory-package": {
    kind: "inventory-package",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["inventory-record", "inventory-audit", "set", "generated-output", "document"],
  },
  vendor: {
    kind: "vendor",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "asset",
      "purchase-order",
      "production-cost",
      "shipment",
      "transport-order",
      "return",
      "location",
      "document",
      "generated-output",
      "vendor-contact",
      "vendor-agreement",
      "brokerage-record",
      "communication",
      "distribution-list",
    ],
  },
  "vendor-contact": {
    kind: "vendor-contact",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["vendor"],
  },
  "vendor-agreement": {
    kind: "vendor-agreement",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["vendor", "purchase-order", "document"],
  },
  "purchase-order": {
    kind: "purchase-order",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "vendor",
      "budget-requirement",
      "set",
      "department",
      "purchase-line",
      "purchase-package",
      "asset",
      "shipment",
      "return",
      "generated-output",
      "brokerage-record",
      "production-cost",
      "communication",
    ],
  },
  "purchase-line": {
    kind: "purchase-line",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["purchase-order", "asset", "budget-requirement"],
  },
  "purchase-package": {
    kind: "purchase-package",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["purchase-order", "source-document", "document", "generated-output", "brokerage-record"],
  },
  "brokerage-record": {
    kind: "brokerage-record",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "shipment",
      "vendor",
      "set",
      "asset",
      "purchase-order",
      "return",
      "brokerage-line",
      "brokerage-package",
      "generated-output",
    ],
  },
  "brokerage-line": {
    kind: "brokerage-line",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["brokerage-record", "asset"],
  },
  "brokerage-package": {
    kind: "brokerage-package",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["brokerage-record", "source-document", "document", "generated-output"],
  },
  "production-cost": {
    kind: "production-cost",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "show",
      "episode",
      "set",
      "department",
      "scene",
      "budget-requirement",
      "vendor",
      "purchase-order",
      "asset",
      "shipment",
      "brokerage-record",
      "return",
      "transport-order",
      "shoot-day",
      "department-cost",
      "document",
    ],
  },
  "department-cost": {
    kind: "department-cost",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "show",
      "episode",
      "department",
      "set",
      "budget-requirement",
      "production-cost",
      "cost-report",
    ],
  },
  "cost-report": {
    kind: "cost-report",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "show",
      "episode",
      "set",
      "department",
      "department-cost",
      "cost-report-package",
      "generated-output",
      "document",
    ],
  },
  "cost-report-package": {
    kind: "cost-report-package",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["cost-report", "generated-output", "document"],
  },
  "transport-order": {
    kind: "transport-order",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "shoot-day",
      "asset",
      "vendor",
      "shipment",
      "production-cost",
      "communication",
      "inventory-movement",
    ],
  },
  shipment: {
    kind: "shipment",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "purchase-order",
      "shipment-stop",
      "shipment-event",
      "shipment-package",
      "vendor",
      "asset",
      "location",
      "return",
      "generated-output",
      "transport-order",
      "set",
      "brokerage-record",
      "communication",
      "inventory-movement",
    ],
  },
  "shipment-stop": {
    kind: "shipment-stop",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["shipment", "location"],
  },
  "shipment-event": {
    kind: "shipment-event",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["shipment", "location", "shipment-stop"],
  },
  "shipment-package": {
    kind: "shipment-package",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["shipment", "source-document", "document", "generated-output"],
  },
  return: {
    kind: "return",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "return-line",
      "return-package",
      "asset",
      "vendor",
      "purchase-order",
      "shipment",
      "brokerage-record",
      "generated-output",
      "set",
      "communication",
    ],
  },
  "return-line": {
    kind: "return-line",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["return", "asset"],
  },
  "return-package": {
    kind: "return-package",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["return", "source-document", "document", "generated-output"],
  },
  "source-document": {
    kind: "source-document",
    isImmutableSource: true,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["document-revision", "show", "shoot-day", "scene", "location", "asset", "person", "vendor"],
  },
  document: {
    kind: "document",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "show",
      "scene",
      "set",
      "shoot-day",
      "callsheet",
      "production-calendar",
      "asset",
      "shipment",
      "brokerage-record",
      "return",
      "vendor",
      "purchase-order",
      "location",
      "document-revision",
      "document-package",
      "document-link",
      "generated-output",
    ],
  },
  "document-revision": {
    kind: "document-revision",
    isImmutableSource: true,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["document", "source-document"],
  },
  "document-package": {
    kind: "document-package",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["source-document", "document", "generated-output"],
  },
  "document-link": {
    kind: "document-link",
    isImmutableSource: false,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: [
      "document",
      "scene",
      "set",
      "asset",
      "shipment",
      "brokerage-record",
      "return",
      "vendor",
      "purchase-order",
      "location",
      "callsheet",
      "production-calendar",
    ],
  },
  "generated-output": {
    kind: "generated-output",
    isImmutableSource: false,
    isDerivedOnly: true,
    isCalendarAuthority: false,
    relationshipTargets: [
      "source-document",
      "document",
      "document-package",
      "production-calendar",
      "calendar-day",
      "calendar-package",
      "shoot-day",
      "callsheet",
      "callsheet-package",
      "work-order",
      "work-order-task",
      "work-order-package",
      "transport-order",
      "shipment",
      "shipment-package",
      "return",
      "return-package",
      "production-cost",
      "department-cost",
      "cost-report",
      "cost-report-package",
      "communication",
      "communication-package",
      "distribution-list",
      "inventory-record",
      "inventory-package",
    ],
  },
  media: {
    kind: "media",
    isImmutableSource: true,
    isDerivedOnly: false,
    isCalendarAuthority: false,
    relationshipTargets: ["scene", "shoot-day", "location", "asset", "person"],
  },
  "risk-evaluation": {
    kind: "risk-evaluation",
    isImmutableSource: false,
    isDerivedOnly: true,
    isCalendarAuthority: false,
    relationshipTargets: ["shoot-day", "location", "asset", "shipment", "vendor"],
  },
};
